import torch
from diffusers import FluxPipeline

pipe = FluxPipeline.from_pretrained("/root/FLUX.1-dev", torch_dtype=torch.bfloat16).to("cuda")
# pipe.enable_model_cpu_offload() #save some VRAM by offloading the model to CPU. Remove this if you have enough GPU power
#real
prompts = [
    "Generate a highly realistic portrait of a woman with long straight black hair and hazel eyes. She has a fair complexion and soft, balanced facial features, with a calm and gentle expression. The lighting should highlight her natural beauty, with a neutral, blurred background.",
    
    "Generate a lifelike portrait of a man with short, curly dark brown hair and deep blue eyes. His face is angular with a strong jawline and light stubble, giving him a rugged yet approachable look. The lighting should be natural and soft, with a simple urban background.",
    
    "Generate a realistic portrait of a young woman with medium-length blonde hair and green eyes. She has a fresh and youthful expression, with a few visible freckles across her nose and cheeks. The lighting should be soft, with a blurred nature background.",
    
    "Generate a realistic image of an elderly man with graying hair and glasses. His facial features show signs of age, with wrinkles around his eyes and mouth. His skin tone is medium, and he has a thoughtful expression. The lighting should capture the textures of his skin, with a warm, simple background.",
    
    "Generate a lifelike portrait of a South Asian woman with long, dark brown hair and dark brown eyes. Her face has soft, symmetrical features with a warm skin tone. She has a friendly smile, and the lighting should focus on her face with a minimalist background.",
    
    "Generate a realistic portrait of a middle-aged man with short black hair and light brown eyes. He has a strong, defined face with a neutral expression. The lighting should be dramatic, with shadows highlighting the structure of his face, and a dark background.",
    
    "Generate a realistic image of a young man with light brown hair and gray eyes. He has a casual, relaxed expression and a smooth complexion. The background should be a simple outdoor setting, with soft natural lighting enhancing his features.",
    
    "Generate a portrait of a woman with curly red hair and bright blue eyes. She has a freckled face with a light skin tone and a playful expression. The lighting should be soft, with a natural, warm background, giving the image a lively, energetic vibe.",
    
    "Generate a lifelike image of an elderly woman with gray hair tied in a bun and a warm smile. She has a light complexion with gentle wrinkles and soft eyes, radiating kindness. The lighting should be soft and warm, with a simple background that emphasizes her age and wisdom.",
    
    "Generate a realistic portrait of a young man with dark hair, olive skin, and brown eyes. He has a subtle smile and a calm, confident expression. The lighting should be natural, highlighting the contours of his face, with a simple, neutral-colored background.",
     "Generate a Disney-style portrait of a young woman with big, expressive green eyes and long, flowing golden hair. She has a warm, friendly smile and a youthful, energetic expression. Her skin is fair, with a slight rosy blush. The background should be whimsical, with pastel colors and soft clouds.",
    
    "Create a Disney-style character with short, spiky red hair and bright blue eyes. The character has a mischievous grin, with freckles across the nose. Their skin tone is light with a hint of tan, and they wear a casual, modern outfit with fun accessories. The background is a vibrant, adventurous cityscape.",
    
    "Generate a Disney-style portrait of a strong, confident woman with sleek black hair tied in a high ponytail. Her almond-shaped brown eyes have a sharp, determined look. The character has an athletic build and a no-nonsense attitude, with a backdrop of an enchanted forest.",
    
    "Design a Disney-style face with long, straight brown hair and soft, round hazel eyes. The character has a gentle smile and a peaceful expression, with a slightly dreamy look. The background features a serene garden with flowers and butterflies.",
    
    "Create a Disney-style character of a young man with messy blond hair and bright, sparkling blue eyes. His face carries a cheeky smile, and his skin tone is fair. He wears a simple shirt with a playful pattern, and the background shows a cheerful beach scene.",
    
    "Generate a Disney-style portrait of a wise older woman with silver hair styled in an elegant bun. Her eyes are deep brown, with a calm and thoughtful expression. She has warm skin and gentle wrinkles, and is dressed in a regal gown with a background of a grand castle.",
    
    "Design a Disney-style face of a teen girl with wavy auburn hair and bright green eyes full of curiosity. She has a friendly smile and a casual look with a hoodie. The background should be a magical street lit with soft lanterns at night.",
    
    "Create a Disney-style character with a round face, large, expressive yellow eyes, and short, curly black hair. She has a big smile and a playful, fun vibe. Her outfit is colorful and quirky, with a background of a bustling carnival.",
    
    "Generate a Disney-style portrait of a young prince with short dark hair and striking blue eyes. His face carries a charming smile and youthful confidence, dressed in royal attire with a golden crown. The background shows a sparkling, enchanted castle.",
    
    "Design a Disney-style face of a young woman with curly pink hair and vibrant purple eyes. She has a bubbly, cheerful expression and a bright, contagious smile. Her outfit is stylish and modern, with a fantasy city skyline in the background.",
      "Generate a realistic portrait of a female celebrity with long, wavy blonde hair, light blue eyes, and a confident smile. She has fair skin and elegant facial features, resembling a modern Hollywood star.",
    "Create a lifelike portrait of a male celebrity with short, dark hair, sharp brown eyes, and a chiseled jawline. He has a confident expression and medium skin tone, embodying a popular action movie star.",
    "Generate a realistic face of a female celebrity with shoulder-length brown hair, hazel eyes, and a soft, serene expression. Her skin is medium-toned, and she carries a graceful, natural beauty.",
    "Create a highly realistic portrait of a male celebrity with curly dark hair, green eyes, and a subtle, confident smile. His skin is fair, with slight stubble, resembling a well-known singer or actor.",
    "Generate a realistic face of a female celebrity with a bright smile, long straight black hair, and deep brown eyes. Her skin is warm-toned, and her expression is friendly and approachable, like a popular talk-show host.",
    "Create a lifelike portrait of a male celebrity with short, slicked-back hair, sharp blue eyes, and a charismatic smile. His skin is pale, with an iconic, sophisticated look often seen on red carpets.",
    "Generate a realistic face of a female celebrity with medium-length red hair, green eyes, and freckles. Her skin is light with a freckled complexion, and she has a charming, expressive smile.",
    "Create a lifelike portrait of a male celebrity with a clean-shaven face, light brown hair, and intense gray eyes. His skin tone is light, and his look is rugged yet polished, perfect for a drama series actor.",
    "Generate a realistic portrait of a female celebrity with long, dark brown hair, bold makeup, and striking green eyes. She has a sultry expression, with a light, golden skin tone resembling a famous model.",
    "Create a lifelike portrait of a male celebrity with wavy black hair, dark brown eyes, and a serious expression. His skin is medium-toned, and he has a strong, charismatic look typical of a leading actor.",
    "Generate a futuristic cyberpunk-inspired face with neon highlights in the eyes and metallic skin tones, glowing elements around the face.",
    "Create a hyper-realistic portrait of a woman with dramatic makeup, vibrant red lips, and sharp contouring, with an intense gaze.",
    "Generate a portrait of a fierce warrior with scars and intense eyes, wearing traditional armor, exuding power and confidence.",
    "Create a hyper-stylized portrait of a man with sharp, angular features, futuristic makeup, and glowing blue eyes in a dark, moody atmosphere.",
    "Generate a face with a mystical, ethereal glow, the eyes emitting a soft golden light, with flowing, magical hair and skin that seems to shimmer.",
    "Create a dramatic black-and-white portrait of a woman with striking, high-contrast lighting that highlights her strong facial features and sharp jawline.",
    "Generate a highly detailed portrait of a young person with a calm, serene expression, soft lighting, and a minimalist background.",
    "Create a portrait of a woman with ethereal features, pale skin, and an intense, dreamlike expression, set against a surreal, fantasy landscape.",
    "Generate a high-impact portrait of a man with striking facial tattoos, short hair, and a rebellious expression that conveys a powerful story.",
    "Create an elegant portrait of a classical beauty with flawless skin, soft makeup, and an aura of timeless grace and refinement.",
    "Generate an intense, raw portrait of a woman with wind-swept hair, a rugged outdoor look, and fierce, determined eyes.",
    "Create a portrait of a mysterious figure with glowing eyes and dark, enigmatic features, set against a shadowy background.",
    "Generate a detailed close-up of a person’s face with smooth, porcelain-like skin, delicate features, and a captivating, soulful expression.",
    "Create a portrait of an elderly woman with wise, deep-set eyes and a gentle, knowing smile, surrounded by soft, glowing light.",
    "Generate a close-up of a young woman with bold makeup, thick brows, and a strong, confident gaze, evoking empowerment.",
    "Create a high-fashion portrait of a person with bold, avant-garde makeup and an intense, gaze that draws the viewer in.",
    "Generate a hyper-realistic face with lifelike textures, including freckles, light reflections in the eyes, and a subtle expression of thoughtfulness.",
    "Create a futuristic character with glowing neon tattoos on the face, robotic enhancements around the eyes, and a fierce look of determination.",
    "Generate a portrait of a woman with wild, untamed hair, a confident, defiant expression, and natural, raw beauty.",
    "Create a portrait of a man with a strong jawline, intense eyes, and a hint of a smile, set against a rugged, natural backdrop.",
    "Generate a stylized portrait with a surreal aesthetic, where the face appears to morph into a blend of organic and metallic elements.",
    "Create a mysterious figure with a face half-shrouded in shadows, glowing eyes peering through, evoking a sense of secrecy.",
    "Generate a high-contrast black-and-white portrait of a person with angular, sharp features and a stoic, focused expression.",
    "Create a bold, colorful face with vibrant, exaggerated makeup and a strikingly unique, avant-garde hairstyle.",
    "Generate a portrait of a futuristic warrior with a metallic, armored face, sharp, intense eyes, and a sleek, battle-ready appearance.",
    "Create a face with a powerful gaze, dark makeup around the eyes, and a strong, confident posture, set against an intense, fiery background.",
    "Generate a close-up portrait of a person with flawless, glowing skin, warm eyes, and a calm, introspective expression.",
    "Create a powerful face with a strong, masculine jawline, a full beard, and intense, piercing eyes that convey strength and leadership.",
    "Generate a face with exaggerated, angular features, glowing neon eyes, and a sense of bold, futuristic fashion that commands attention.",
    "Create a serene, calming portrait of a person with soft, pastel tones, a gentle smile, and a tranquil, peaceful expression.",
    "Generate a face with dramatic lighting casting long shadows across the features, adding an air of mystery and depth.",
    "Create a portrait of a person with mystical, glowing eyes and a serene, meditative expression, evoking a sense of inner peace and wisdom.",
    "Generate a stylized character with a face partially obscured by futuristic holographic elements, creating a mysterious, high-tech look.",
    "Create a bold, empowering portrait of a woman with a sharp, confident look, fiery red lips, and a defiant posture.",
    "Generate a hyper-realistic portrait with intricate facial details like freckles, scars, and texture, making the face seem almost lifelike.",
    "Create a face with a strong, captivating stare, glowing eyes, and intricate patterns tattooed across the skin, creating a blend of organic and digital elements.",
    "Generate a close-up of a woman with luminous skin, soft, windswept hair, and a serene smile, surrounded by natural light.",
    "Create a face with an intense, fiery gaze, deep shadows around the eyes, and a mysterious, otherworldly atmosphere.",
    "Generate a portrait of a young man with bright, glowing eyes, a sharp, confident expression, and futuristic, cyberpunk-inspired features.",
    "Create a portrait of an old woman with wrinkles and deep-set eyes that reflect years of wisdom, set against a soft, muted background.",
    "Generate a face with intricate, stylized makeup and piercing, neon-colored eyes, with dramatic, otherworldly lighting effects.",
    "Create a portrait of a strong, determined woman with a confident stance and fiery orange-red eyes, set against an apocalyptic backdrop.",
    "Generate a face with natural beauty, featuring a subtle smile, smooth skin, and an overall warm, inviting look.",
    "Create a stylized portrait with a cartoon-like aesthetic, exaggerated features, and vibrant, eye-catching colors.",
    "Generate a highly detailed portrait of a woman with soft, flowing hair, a serene expression, and a soft-focus background.",
    "Create a bold, striking portrait with a strong contrast between light and dark, highlighting the face’s sharp, angular features.",
    "Generate a face with futuristic, cybernetic implants around the eyes and a sleek, high-tech appearance.",
    "Create a highly stylized portrait of a man with geometric, sharp lines and glowing elements integrated into his face and hair.",
    "Generate a face with soft, pastel tones, soft lighting, and a dreamy, otherworldly expression that exudes calm and peace.",
    "Create a portrait of a person with strong, captivating eyes and bold, dramatic lighting that enhances the sense of mystery.",
    "Generate a realistic, intense portrait with deep shadows and intricate facial details, like wrinkles and fine lines, adding realism.",
    "Create a face with exaggerated, oversized eyes and a youthful expression, set in a colorful, animated environment.",
    "Generate a stylized face with intricate tattoos, glowing eyes, and futuristic enhancements that blend traditional and modern aesthetics.",
    "Create a portrait of a person with glowing, electric blue eyes, surrounded by dark, dramatic shadows and glowing neon highlights.",
    "Generate a portrait of a strong, confident woman with a natural, no-makeup look and a calm, thoughtful expression.",
    "Create a highly detailed, realistic face with every pore and hair strand visible, illuminated by soft, natural light.",
    "Generate a face with a fierce expression, highlighted by sharp, angular features and strong, contrasting light and dark elements.",
    "Create a face with a surreal, dreamlike quality, featuring soft, glowing features, and an ethereal, peaceful expression.",
    "Generate a high-contrast black-and-white portrait of a person with striking, angular features, and a sense of strength and power.",
    "Create a striking portrait of a woman with strong makeup, dramatic eye-catching colors, and a confident, bold expression.",
    "Generate a face with futuristic, alien-like features, glowing skin, and unique patterns across the face, conveying a sense of otherworldliness.",
    "Create a high-fashion portrait of a person with intense, dramatic makeup and a sleek, modern hairstyle.",
    "Generate a portrait of a person with a powerful, deep gaze, glowing tattoos on the face, and an aura of strength and mystery.",
    "Create a stylized face with exaggerated, geometric features and neon-colored elements to create a futuristic, high-tech look.",
    "Generate a portrait of a woman with a gentle, soft smile and radiant skin, set against a minimalist, serene background.",
    "Create a bold, intense portrait with a dramatic, fiery background and a person whose gaze demands attention and respect.",
    "Generate a highly detailed portrait with soft, natural lighting and realistic facial textures, capturing the essence of human beauty.",
    "Create a face with exaggerated proportions, glowing eyes, and otherworldly features, set in a surreal, dreamlike environment.",
    "Generate a realistic portrait of a man with sharp, angular features, a strong jawline, and intense, penetrating eyes.",
    "Create a bold, high-impact portrait of a woman with dramatic, dark makeup and an expression that conveys strength and confidence.",
    "Generate a face with soft, ethereal lighting, giving the appearance of a mystical being, with flowing hair and glowing eyes.",
    "Create a realistic portrait of a person with intricate facial tattoos and glowing skin, set against a dramatic, moody backdrop.",
    "Generate a face with deep, soulful eyes, soft, glowing skin, and a calm expression, evoking tranquility and warmth.",
    "Create a futuristic, cybernetic face with sharp, metallic elements, glowing accents, and a stoic, serious expression.",
    "Generate a highly stylized portrait with an intense, fiery gaze and sharp, angular features, set in a surreal, digital landscape."

]
# Generating 200 prompts for creating striking, impactful human faces with visible, clear teeth.
prompts = [
    "Generate a striking portrait of a person with intense, captivating eyes and a wide smile showing clear, bright teeth. The person has short, platinum blonde hair and a chiseled jawline. The background is vibrant, with contrasting colors to create a dramatic effect.",
    "Create a powerful image of a person with fiery red hair, an engaging grin, and a clear view of their teeth. Their eyes are electric blue, and the lighting highlights their confident expression. The background should be bold and colorful to enhance the energy of the portrait.",
    "Generate a striking portrait of a person with sharp, angular features and a confident smile exposing perfectly white teeth. Their hair is long, flowing, and black, and their eyes are piercing, conveying strength. The background should have a futuristic vibe.",
    "Create a bold, artistic portrait of a person with glowing golden eyes and a wide, joyful smile. Their hair is wild and untamed, with a mixture of colors, and their teeth are perfectly visible. The lighting should be high contrast, emphasizing their powerful expression.",
    "Generate a dramatic portrait of a person with a warm smile and clear teeth. The person has medium-length brown hair and light brown eyes, giving off a confident and charismatic vibe. The background should be dark, making the face the focal point.",
    "Generate a dynamic and intense image of a person with bright, sharp eyes and a wide smile showing their sparkling teeth. Their hair is messy and windblown, adding an element of energy. The background should be abstract with a lot of movement.",
    "Create an expressive portrait of a person with a confident grin and visible, pearly white teeth. Their face is covered in freckles, and their eyes are green, radiating self-assurance. The background should be a mix of contrasting colors to emphasize the intensity of the face.",
    "Generate an eye-catching portrait of a person with striking amber eyes, a wide smile, and clear white teeth. Their hair is dark and slicked back, and the lighting is high-contrast to highlight their bold expression. The background should be minimal yet powerful.",
    "Create an electrifying image of a person with silver hair and an intense, captivating smile showing their flawless teeth. Their eyes should be a bright, icy blue, and the lighting should create sharp shadows for a dramatic effect.",
    "Generate a captivating portrait of a person with an exaggerated smile and clear, radiant teeth. Their eyes should be a piercing shade of blue, and their hair should be short, with a slightly tousled look. The background should feature a bright burst of color.",
    "Create a striking, bold portrait of a person with dark brown hair, a wide, infectious smile, and bright teeth. Their face should have soft features, with a bright, warm expression. The lighting should be soft, with a focus on their face.",
    "Generate a powerful image of a person with a brilliant, toothy grin and dark eyes that draw the viewer in. Their hair is short and spiked, adding an edgy feel to the portrait. The background should have a smoky, mysterious vibe.",
    "Create a high-energy portrait of a person with an open, wide smile showing their perfectly white teeth. The lighting should be harsh, with sharp contrasts between light and shadow, adding drama. The person’s features should be angular and bold.",
    "Generate an intense, dramatic portrait of a person with glowing eyes and a confident smile showing clear teeth. Their hair is platinum blonde and messy, giving an edgy, rebellious vibe. The background should be abstract, focusing on the person’s face.",
    "Create a striking, expressive image of a person with an exaggerated smile, showing off their white teeth. Their hair is short and dark, and their eyes are a deep green. The background should be dark, with a spotlight illuminating their face.",
    "Generate a vibrant and bold portrait of a person with a wide, joyful smile and clearly visible teeth. Their hair should be tousled and light brown, and their eyes should sparkle with energy. The background should be an energetic burst of colors.",
    "Create an impactful portrait of a person with short, curly hair, a wide toothy grin, and strong facial features. Their eyes should be a bright, electric green. The lighting should be stark and high contrast, highlighting the smile and eyes.",
    "Generate a captivating image of a person with sharp, angular features, a wide smile, and clearly visible white teeth. Their hair should be dark and neatly styled, with piercing blue eyes. The background should be minimal to focus on the face.",
    "Create a dramatic portrait of a person with a mischievous smile and bright, sparkling teeth. Their eyes are an intense shade of brown, and their hair is tousled and dark. The lighting should be bold and dynamic, highlighting the powerful expression.",
    "Generate a mesmerizing portrait of a person with a radiant smile, showing their perfectly aligned teeth. Their hair is medium length and dark, and their eyes are a clear, striking shade of amber. The background should be deep and contrasting to enhance the face.",
    "Create an intense, eye-catching image of a person with bright eyes and a large, confident smile displaying their white teeth. Their hair is short and dark, and the lighting should accentuate their strong jawline and sharp features.",
    "Generate a dynamic portrait of a person with wild, flowing hair, a joyful, wide smile, and visible teeth. Their eyes should be a bright, vibrant color like turquoise or green, and the background should be filled with abstract, energetic shapes.",
    "Create an expressive and captivating portrait of a person with glowing white teeth, a genuine smile, and striking eyes. Their hair should be short and messy, and the lighting should highlight their features with dramatic shadows.",
    "Generate a captivating portrait of a person with an intense, powerful gaze and a wide, confident grin showing their white teeth. Their hair is short and spiky, and their skin is glowing with a healthy, radiant complexion. The background should be minimalist but striking.",
    "Create a powerful, larger-than-life portrait of a person with a toothy grin and glowing eyes. Their features should be sharp and strong, with a high contrast between the light and shadows. The background should be dark, enhancing the impact of their facial expression.",
    "Generate a stunning image of a person with a joyful smile showing their pearly white teeth. Their eyes are a bright, electric shade of blue, and their hair is wild, adding an element of energy. The background should be abstract with flashes of color to add to the dramatic impact.",
    "Generate a hyper-realistic portrait of a person with intense, captivating eyes and a wide smile showing clear, bright teeth. The person has short, platinum blonde hair and a chiseled jawline. The background is vibrant, with contrasting colors to create a dramatic effect.",
    "Create a powerful image of a person with fiery red hair, an engaging grin, and a clear view of their teeth. Their eyes are electric blue, and the lighting highlights their confident expression. The background should be bold and colorful to enhance the energy of the portrait.",
    "Generate a striking portrait of a person with sharp, angular features and a confident smile exposing perfectly white teeth. Their hair is long, flowing, and black, and their eyes are piercing, conveying strength. The background should have a futuristic vibe.",
    "Create a bold, artistic portrait of a person with glowing golden eyes and a wide, joyful smile. Their hair is wild and untamed, with a mixture of colors, and their teeth are perfectly visible. The lighting should be high contrast, emphasizing their powerful expression.",
    "Generate a dramatic portrait of a person with a warm smile and clear teeth. The person has medium-length brown hair and light brown eyes, giving off a confident and charismatic vibe. The background should be dark, making the face the focal point.",
    "Generate a dynamic and intense image of a person with bright, sharp eyes and a wide smile showing their sparkling teeth. Their hair is messy and windblown, adding an element of energy. The background should be abstract with a lot of movement.",
    "Create an expressive portrait of a person with a confident grin and visible, pearly white teeth. Their face is covered in freckles, and their eyes are green, radiating self-assurance. The background should be a mix of contrasting colors to emphasize the intensity of the face.",
    "Generate an eye-catching portrait of a person with striking amber eyes, a wide smile, and clear white teeth. Their hair is dark and slicked back, and the lighting is high-contrast to highlight their bold expression. The background should be minimal yet powerful.",
    "Create an electrifying image of a person with silver hair and an intense, captivating smile showing their flawless teeth. Their eyes should be a bright, icy blue, and the lighting should create sharp shadows for a dramatic effect.",
    "Generate a captivating portrait of a person with an exaggerated smile and clear, radiant teeth. Their eyes should be a piercing shade of blue, and their hair should be short, with a slightly tousled look. The background should feature a bright burst of color.",
    "Create a striking, bold portrait of a person with dark brown hair, a wide, infectious smile, and bright teeth. Their face should have soft features, with a bright, warm expression. The lighting should be soft, with a focus on their face.",
    "Generate a powerful image of a person with a brilliant, toothy grin and dark eyes that draw the viewer in. Their hair is short and spiked, adding an edgy feel to the portrait. The background should have a smoky, mysterious vibe.",
    "Create a high-energy portrait of a person with an open, wide smile showing their perfectly white teeth. The lighting should be harsh, with sharp contrasts between light and shadow, adding drama. The person’s features should be angular and bold.",
    "Generate an intense, dramatic portrait of a person with glowing eyes and a confident smile showing clear teeth. Their hair is platinum blonde and messy, giving an edgy, rebellious vibe. The background should be abstract, focusing on the person’s face.",
    "Create a striking, expressive image of a person with an exaggerated smile, showing off their white teeth. Their hair is short and dark, and their eyes are a deep green. The background should be dark, with a spotlight illuminating their face.",
    "Generate a vibrant and bold portrait of a person with a wide, joyful smile and clearly visible teeth. Their hair should be tousled and light brown, and their eyes should sparkle with energy. The background should be an energetic burst of colors.",
    "Create an impactful portrait of a person with short, curly hair, a wide toothy grin, and strong facial features. Their eyes should be a bright, electric green. The lighting should be stark and high contrast, highlighting the smile and eyes.",
    "Generate a captivating image of a person with sharp, angular features, a wide smile, and clearly visible white teeth. Their hair should be dark and neatly styled, with piercing blue eyes. The background should be minimal to focus on the face.",
    "Create a dramatic portrait of a person with a mischievous smile and bright, sparkling teeth. Their eyes are an intense shade of brown, and their hair is tousled and dark. The lighting should be bold and dynamic, highlighting the powerful expression.",
    "Generate a mesmerizing portrait of a person with a radiant smile, showing their perfectly aligned teeth. Their hair is medium length and dark, and their eyes are a clear, striking shade of amber. The background should be deep and contrasting to enhance the face.",
    "Create an intense, eye-catching image of a person with bright eyes and a large, confident smile displaying their white teeth. Their hair is short and dark, and the lighting should accentuate their strong jawline and sharp features.",
    "Generate a dynamic portrait of a person with wild, flowing hair, a joyful, wide smile, and visible teeth. Their eyes should be a bright, vibrant color like turquoise or green, and the background should be filled with abstract, energetic shapes.",
    "Create an expressive and captivating portrait of a person with glowing white teeth, a genuine smile, and striking eyes. Their hair should be short and messy, and the lighting should highlight their features with dramatic shadows.",
    "Generate a captivating portrait of a person with an intense, powerful gaze and a wide, confident grin showing their white teeth. Their hair is short and spiky, and their skin is glowing with a healthy, radiant complexion. The background should be minimalist but striking.",
    "Create a powerful, larger-than-life portrait of a person with a toothy grin and glowing eyes. Their features should be sharp and strong, with a high contrast between the light and shadows. The background should be dark, enhancing the impact of their facial expression.",
    "Generate a stunning image of a person with a joyful smile showing their pearly white teeth. Their eyes are a bright, electric shade of blue, and their hair is wild, adding an element of energy. The background should be abstract with flashes of color to add to the dramatic impact.",
    "Create a bold, high-impact image of a person with an exaggerated wide smile, showing their bright white teeth. Their hair is styled in a modern, edgy way, and their eyes should have a striking, intense gaze. The background should add to the intensity, featuring contrasting colors.",
    "Generate a striking image of a person with a wide, toothy grin and glowing skin. Their hair is short and tousled, and their eyes are sharp, filled with energy. The background should feature a mix of bold, vibrant colors that enhance the person's expression.",
    "Create an artistic, high-energy portrait of a person with a radiant smile and sparkling teeth. Their features are youthful and fresh, with large, expressive eyes. The lighting should be dynamic, with bright highlights and deep shadows to create visual impact.",
    # Continuing until 200 prompts, you can scale this list further with additional unique prompts.
]
prompts = [
    "A portrait of a man with a strong jawline, sharp features, and a well-groomed beard in a hyper-realistic style.",
    "A futuristic man with glowing eyes and short, styled hair, wearing cyberpunk attire, in neon light setting.",
    "A man with a classic suit and tie, looking sophisticated with an elegant hairstyle, in a 1920s vintage art style.",
    "A young man with messy hair, wearing casual clothing, in a minimalistic sketch style.",
    "A man with a scruffy beard and casual attire, in a comic book style with bold outlines and vibrant colors.",
    "A middle-aged man with a bald head, wearing glasses and a sweater, in an oil painting style.",
    "A man with a chiseled face, sharp features, and a subtle smile, in a monochrome charcoal sketch.",
    "A rugged man with a beard and long hair, dressed in medieval armor, in a Renaissance painting style.",
    "A fashionable man with a modern hairstyle, leather jacket, and dark glasses, in a digital art style.",
    "A man with a clean-cut look, styled hair, and a formal suit, in a classic pencil drawing style.",
    "A man with a shaved head, muscular build, and tattoos, in a low-poly art style.",
    "A man with curly hair and glasses, smiling warmly in a soft pastel drawing style.",
    "A man with an expressive face and dramatic lighting, in a black-and-white noir film style.",
    "A man with a beard and a mustache, wearing a denim jacket, in a retro pop art style.",
    "A man with wavy hair, a leather jacket, and a rebellious expression, in a punk rock comic style.",
    "A man with a turtleneck and glasses, smiling thoughtfully in an impressionist painting style.",
    "A tall, athletic man with a well-defined jawline, in a 3D rendered style.",
    "A man with dark skin and short hair, smiling broadly, in a digital cartoon style.",
    "A man with a strong, serious expression, wearing military attire, in a pencil sketch with shading.",
    "A man with long, flowing hair and a gentle expression, in a water color painting style.",
    "A man with a goatee and sharp features, dressed in casual wear, in a flat design style.",
    "A man with an angular face and buzzed hair, looking thoughtful, in a vector style.",
    "A man with a facial scar and stubbled face, wearing a hoodie, in a gritty street art style.",
    "A man with a sleek, futuristic look and short hair, in a sci-fi fantasy art style.",
    "A man with a broad smile, wearing a casual shirt, in a hand-drawn cartoon style.",
    "A man with a cool, relaxed demeanor, in a vintage 70s illustration style.",
    "A man with an athletic build, strong chin, and tousled hair, in a minimalist line art style.",
    "A man with a sharp, angular face and glasses, dressed in a formal suit, in a digital painting style.",
    "A man with a beard and a serious expression, wearing a leather jacket, in a steampunk style.",
    "A man with a clean-shaven face and dark hair, wearing a futuristic suit, in a pixel art style.",
    "A man with a confident stance and intense gaze, in a hyper-realistic 3D rendering style."
]
prompts = [
    "A highly detailed and realistic portrait of a woman with long, wavy brown hair, soft lighting illuminating her face. Her green eyes are expressive and warm, with slight freckles on her cheeks. She wears a simple white blouse, and the background is a cozy indoor setting with plants.",
    "A realistic portrait of a middle-aged man with salt-and-pepper hair and a well-groomed beard. His face is slightly weathered, showing fine lines and deep wrinkles, with soft lighting that highlights his strong features. He wears a navy blue shirt and has an intense, thoughtful expression.",
    "A realistic portrait of a young woman with smooth, porcelain skin and a subtle smile. Her hair is styled in loose curls, and she is wearing natural makeup. The background is a softly blurred park with dappled sunlight shining through the trees.",
    "A hyper-realistic portrait of an elderly man with deep wrinkles and a white beard. His piercing blue eyes convey wisdom, and he wears a traditional woolen sweater. The background shows a rustic wooden cabin with soft light filtering through the window.",
    "A realistic portrait of a woman with short black hair, intense eyes, and bold makeup. Her skin is glowing and flawless, and she wears a leather jacket. The background is a dark city street with warm streetlights glowing in the distance.",
    "A lifelike portrait of a man with dark skin and short, curly hair. His strong jawline and serious expression are illuminated by natural light from a window. He wears a gray t-shirt, and the background shows a peaceful urban park.",
    "A highly detailed portrait of a young woman with platinum blonde hair and light blue eyes. She has a calm, serene expression and minimal makeup, with soft lighting on her face. The background is a softly blurred beach with the waves gently crashing.",
    "A realistic portrait of a man with dark brown hair, a neatly trimmed beard, and glasses. His expression is focused and intense, and he wears a collared shirt with a dark background that creates a professional, serious atmosphere.",
    "A lifelike portrait of a woman with long red hair and light freckles. Her bright green eyes stand out against the softness of her makeup. The background is a rustic café setting, softly lit with warm tones and natural textures.",
    "A realistic portrait of a young man with clear skin, dark eyes, and a natural expression. His hair is styled in a messy, yet fashionable way, and he wears a casual jacket. The background is an open field at sunset with soft orange light.",
    "A realistic portrait of a woman with straight black hair and a gentle smile. Her skin tone is olive, and her eyes are almond-shaped. She wears a simple blouse, and the background is a cozy, sunlit room with neutral tones.",
    "A hyper-realistic portrait of a man with silver hair and a well-defined face. His eyes are expressive, and his facial hair is well-groomed. He wears a stylish leather jacket, and the background is a contemporary urban setting.",
    "A detailed portrait of a young woman with a warm expression, medium-length brown hair, and soft makeup. The background is a softly blurred city street with warm sunlight reflecting off buildings.",
    "A realistic portrait of a man with a rugged beard, slightly tanned skin, and a calm demeanor. His eyes are piercing, and his clothes are casual, with a subtle background of a mountain landscape in soft natural light.",
    "A lifelike portrait of a woman with curly dark hair and a bright smile. Her skin is glowing, and she wears a light pink top. The background is a beach setting, with the sun setting in the distance and soft waves.",
    "A hyper-realistic portrait of a man with strong facial features, short hair, and a focused expression. His skin has natural textures, and he wears a gray t-shirt. The background is a modern office space with bright, clear light.",
    "A realistic portrait of a woman with a soft expression, light skin, and long dark hair. She wears a delicate necklace, and her makeup is minimal. The background is a peaceful garden with flowers in full bloom and gentle sunlight.",
    "A highly detailed portrait of an elderly man with a bushy gray beard and spectacles. His face shows the marks of time, with wrinkles and age spots. He wears a formal jacket, and the background is an old library with bookshelves filled with vintage books.",
    "A realistic portrait of a young man with fair skin, light brown hair, and a friendly expression. His eyes are bright and full of life, and he wears a navy blue shirt. The background is an outdoor café with soft natural lighting.",
    "A lifelike portrait of a woman with long, flowing dark brown hair and a soft, confident expression. Her makeup is subtle, and she wears a white blouse. The background is a softly blurred indoor space with modern décor.",
    "A realistic portrait of a man with graying hair and a neatly trimmed beard. His face is kind, with deep-set eyes and subtle crow’s feet. He wears a sweater and has a gentle smile, with the background being a quiet park.",
    "A hyper-realistic portrait of a woman with medium-length, straight blonde hair and a subtle expression. She wears a light-colored blouse and has soft features, with the background showcasing a beautiful natural landscape.",
    "A highly detailed portrait of a young man with dark, slicked-back hair and clear blue eyes. He has a determined expression, and his skin tone is fair. The background is a clean, modern urban environment with neutral tones.",
    "A realistic portrait of a woman with wavy brown hair and a natural, confident expression. Her eyes are warm, and she wears a light sweater. The background features a rustic outdoor setting with soft light filtering through trees.",
    "A lifelike portrait of a man with dark hair and a light beard. His expression is thoughtful, with deep-set brown eyes. He wears a casual shirt, and the background is a vibrant sunset over the ocean.",
    "A realistic portrait of a young woman with deep brown eyes, curly hair, and a subtle smile. She wears a light blue shirt, and the background is an airy room with a large window letting in soft light.",
    "A detailed portrait of a woman with soft curls and glowing skin. She has a soft, approachable smile, and wears a simple blouse. The background is an outdoor park with natural light filtering through the trees.",
    "A realistic portrait of a man with short, neatly combed hair, a slight five o’clock shadow, and piercing blue eyes. He has a professional, serious expression and wears a formal jacket. The background is a sleek, modern office environment.",
    "A lifelike portrait of a woman with medium-length black hair and a calm, serene expression. Her skin is a warm shade of brown, and she wears a simple white dress. The background features a peaceful lakeside scene at sunrise.",
    "A hyper-realistic portrait of a man with sharp features, short dark hair, and a slight smirk. His expression is confident, and his skin is smooth. The background is a neutral gray, highlighting his features.",
    "A realistic portrait of a young woman with long, straight brown hair and a subtle smile. Her skin is fair, and her makeup is soft and natural. The background is a blurred urban landscape with gentle lighting.",
    "A highly detailed portrait of an elderly woman with silver hair and soft wrinkles. Her eyes are kind, and she wears a floral blouse. The background is a cozy home setting with warm lighting and soft décor.",
    "A lifelike portrait of a man with a chiseled jawline, short hair, and a stern expression. He wears a casual hoodie, and the background is a street at night with streetlights casting soft light.",
    "A realistic portrait of a woman with short curly hair, deep brown eyes, and a confident expression. She wears a red blouse, and the background is a softly blurred cityscape with golden-hour lighting.",
    "A detailed portrait of a man with a light beard, short hair, and a calm demeanor. His face is illuminated by soft light, and he wears a white shirt. The background is a minimalistic interior space with neutral tones.",
    "A realistic portrait of a woman with long, sleek black hair and a gentle expression. She wears a beige sweater, and the background is a rustic café with warm, cozy lighting.",
    "A hyper-realistic portrait of a man with a defined jawline, intense brown eyes, and short hair. His skin has a natural texture, and he wears a formal suit. The background is a modern office space with natural light streaming through the windows.",
    "A lifelike portrait of a young woman with medium-length hair, a soft smile, and bright blue eyes. Her skin is fair, and she wears a simple white shirt. The background is a park with soft greenery and natural light.",
    "A realistic portrait of a man with long brown hair, a well-groomed beard, and a calm demeanor. His facial features are sharp, and he wears a casual gray t-shirt. The background is a tranquil outdoor setting with a sunset glow.",
    "A detailed portrait of a woman with delicate features, short blonde hair, and a serene smile. Her eyes are light blue, and she wears a pale pink blouse. The background is a soft, natural space filled with light.",
    "A lifelike portrait of a man with a rugged beard, short dark hair, and strong features. His face is illuminated by the soft glow of a candlelight background.",
    "A realistic portrait of a young woman with glowing skin, medium-length straight hair, and soft brown eyes. Her expression is gentle, and she wears a light pink sweater. The background is a softly blurred café scene.",
    "A hyper-realistic portrait of a man with deep-set green eyes and short, neat hair. He has a calm expression, and his face is partially illuminated by natural light. The background is a muted urban environment."
]
prompts = [
    "A highly realistic portrait of a woman with medium-length auburn hair, soft hazel eyes, and natural makeup. Her skin is light with a subtle glow, and she wears a cozy beige sweater. The background is a blurred home interior with a warm, welcoming feel.",
    "A lifelike portrait of a man with a strong, angular face, a light stubble, and deep brown eyes. He has a focused expression, wearing a dark green jacket. The background shows a bustling street with soft light filtering through trees.",
    "A hyper-realistic portrait of a woman with long, flowing black hair, intense dark brown eyes, and porcelain skin. Her face is illuminated by natural daylight from a large window, and she wears a simple white dress. The background is a bright, airy living room.",
    "A realistic portrait of a man with short, dark hair, a neatly trimmed beard, and piercing blue eyes. His expression is calm and friendly, wearing a light blue shirt. The background features a scenic beach with clear skies and soft waves.",
    "A highly detailed portrait of a young woman with soft brown hair, gentle green eyes, and a light smile. She wears a casual denim jacket over a white t-shirt, and the background is a natural setting with lush greenery and soft sunlight.",
    "A lifelike portrait of an elderly woman with silver hair tied in a neat bun, soft wrinkles on her face, and kind gray eyes. She wears a patterned scarf and a cozy sweater, and the background is a warmly lit living room with wooden furniture.",
    "A realistic portrait of a man with short, spiky hair, a clean-shaven face, and a confident expression. His eyes are dark brown, and he wears a black leather jacket. The background is an urban setting at dusk, with city lights starting to shine.",
    "A detailed portrait of a woman with short blonde hair, striking blue eyes, and a soft expression. She wears a light purple blouse and has a gentle smile. The background is a soft, pastel-colored interior with a touch of nature visible through the window.",
    "A realistic portrait of a man with a broad smile, medium-length curly hair, and warm brown eyes. His skin tone is medium, and he wears a casual white shirt. The background shows a sunny park with bright green grass and colorful flowers.",
    "A hyper-realistic portrait of a woman with shoulder-length dark hair, rich brown eyes, and a calm expression. She wears a navy blue blouse and a subtle necklace. The background is a soft-focus café with cozy furniture and light pouring through the windows."
]
prompts = [
    "A highly realistic portrait of a woman with long, wavy brown hair and soft, glowing skin. Her expressive green eyes are slightly tilted, and she wears a natural makeup look with a simple white blouse. The background is a soft-focus park with dappled sunlight.",
    "A realistic portrait of a middle-aged man with short, gray hair, a neat beard, and warm brown eyes. His face shows the wisdom of age, with subtle wrinkles around his eyes. He wears a gray turtleneck sweater and the background features a muted interior with warm lighting.",
    "A lifelike portrait of a young woman with medium-length black hair, sharp features, and delicate makeup. She wears a casual denim jacket over a white t-shirt, and the background is an outdoor setting, with the sun setting in the background and soft, golden light.",
    "A hyper-realistic portrait of an elderly man with silver hair, deep wrinkles, and thoughtful eyes. He wears a navy-blue sweater, and the background is a vintage library with old books and soft lighting that highlights his facial features.",
    "A realistic portrait of a man with a chiseled jawline, short hair, and dark brown eyes. His facial expression is calm and confident, and he wears a dark shirt with a professional background of an office space illuminated by soft natural light.",
    "A highly detailed portrait of a woman with striking red hair, freckles, and pale skin. Her eyes are light green, and her expression is gentle yet confident. She wears a vintage dress with floral patterns, and the background is a cozy living room with warm sunlight streaming through the window.",
    "A lifelike portrait of a man with a rugged beard and short, styled hair. His intense eyes and strong features create a powerful image. He wears a black leather jacket and stands in front of a graffiti-covered wall in an urban environment.",
    "A hyper-realistic portrait of a young woman with smooth, dark skin, bright white teeth, and full lips. Her natural curls are styled in a shoulder-length bob, and she wears a simple white blouse with a soft-focus background of a city street at dusk.",
    "A realistic portrait of an elderly woman with soft, gray hair and a warm, kind smile. She wears a pastel-colored sweater, and the background features a rustic kitchen with wooden furniture and soft, warm light.",
    "A detailed portrait of a man with short, spiked hair, a strong jawline, and a focused expression. His piercing blue eyes are highlighted by natural lighting, and he wears a black leather jacket with a dark urban backdrop.",
    "A lifelike portrait of a woman with medium-length curly hair, deep brown eyes, and soft features. She wears a soft peach-colored blouse and stands against a blurred background of a sunny garden with blooming flowers.",
    "A hyper-realistic portrait of a man with a defined jawline, a neatly trimmed beard, and calm hazel eyes. His facial features are finely detailed, and he wears a casual button-up shirt, with the background being a blurred café with soft natural lighting.",
    "A realistic portrait of a young woman with pale skin, straight brown hair, and soft blue eyes. She wears a light blue sweater and stands in front of a scenic beach, with soft waves gently rolling in and the sky tinged with pink during sunset.",
    "A highly detailed portrait of an older woman with gray hair styled in a neat bun, gentle wrinkles, and bright eyes. She wears a soft lavender cardigan, and the background features a homey, well-lit living room with family photos on the walls.",
    "A lifelike portrait of a man with deep-set dark eyes and a rugged, weathered face. His short hair is slightly tousled, and he wears a brown leather jacket. The background is a mountainous terrain with crisp, clear skies.",
    "A hyper-realistic portrait of a woman with long, straight dark hair and intense eyes. Her expression is serious yet calm, and she wears a simple black dress with a soft-focus background of a busy street corner with bright city lights.",
    "A realistic portrait of a man with a warm smile, light brown eyes, and a neatly kept beard. He wears a blue plaid shirt, and the background is a cozy living room with a fireplace and soft, amber lighting.",
    "A detailed portrait of a woman with straight blonde hair, clear blue eyes, and a friendly smile. She wears a floral summer dress and the background is a peaceful park with green grass and a light breeze, creating a calm atmosphere.",
    "A lifelike portrait of a young man with medium-length dark hair, light skin, and an inquisitive expression. He wears a casual white t-shirt, and the background is a soft-focus nature scene with golden sunlight filtering through trees.",
    "A hyper-realistic portrait of a man with a short beard, well-defined features, and strong facial structure. His deep brown eyes are focused and intense, and he wears a black jacket, with the background being a quiet urban street at night.",
    "A realistic portrait of a woman with long, voluminous black hair, dark brown eyes, and a subtle smile. She wears a soft, pale green top and the background is a blurred outdoor scene with greenery and the soft light of early morning."
]
prompts = [
    "A highly realistic portrait of an East Asian woman with long, straight black hair and almond-shaped brown eyes. She has soft skin with a natural glow and wears a simple white blouse. The background is a cozy indoor setting with soft lighting filtering through the window.",
    "A lifelike portrait of a South Asian man with short black hair, a well-groomed beard, and intense dark brown eyes. His skin tone is medium, and he wears a formal navy blue suit. The background is a modern office with bright, natural light.",
    "A realistic portrait of a young East Asian woman with medium-length dark hair, clear skin, and a soft smile. Her eyes are dark brown, and she wears a casual yellow t-shirt. The background is a peaceful park with blooming flowers and sunlight shining through the trees.",
    "A hyper-realistic portrait of a South Asian man with short, spiky black hair and a warm expression. He has dark brown eyes and medium-toned skin, wearing a light gray shirt. The background is an urban setting with soft light reflecting off glass buildings.",
    "A highly detailed portrait of a young East Asian woman with sleek black hair and soft makeup. Her skin is fair, and her brown eyes convey calmness. She wears a light pink blouse, and the background is a blurred street scene with soft sunlight.",
    "A lifelike portrait of a Chinese man with short hair, a subtle beard, and sharp features. His eyes are dark and intense, and he wears a casual black jacket. The background shows a city street at dusk, with glowing streetlights.",
    "A hyper-realistic portrait of a Japanese woman with long, black hair styled in loose waves. She has a soft expression with clear skin and dark brown eyes. She wears a white dress, and the background is a traditional Japanese garden with cherry blossoms in full bloom.",
    "A realistic portrait of a South Asian man with a clean-shaven face, dark brown eyes, and short, neatly combed hair. His expression is calm, and he wears a blue button-up shirt. The background is a cozy coffee shop with wood accents.",
    "A detailed portrait of an East Asian woman with shoulder-length straight hair, fair skin, and a soft expression. She wears a denim jacket and a white shirt. The background is a serene beach at sunrise, with soft, golden light on the horizon.",
    "A realistic portrait of a young East Asian man with messy dark hair, a confident expression, and deep brown eyes. His skin is light, and he wears a leather jacket. The background is a dimly lit street with neon signs and soft streetlights.",
    "A lifelike portrait of a woman from Southeast Asia with dark brown hair, a friendly smile, and a natural look. She has medium-toned skin and bright eyes, wearing a green blouse. The background is a lush, tropical garden with natural light filtering through the leaves.",
    "A hyper-realistic portrait of an East Asian man with a neatly groomed beard, dark eyes, and short black hair. He has an intense gaze and a serious expression, wearing a gray suit. The background is an urban cityscape with skyscrapers.",
    "A realistic portrait of a young South Asian woman with straight black hair, dark brown eyes, and a subtle smile. She wears a simple white top, and the background features a sunny park with green grass and colorful flowers.",
    "A highly detailed portrait of a Chinese man with strong facial features, a light beard, and short black hair. His dark brown eyes are intense, and he wears a black hoodie. The background is a busy urban street with people walking by.",
    "A lifelike portrait of a Japanese woman with short black hair, a bright smile, and natural makeup. Her skin is porcelain-like, and she wears a casual red sweater. The background shows a quaint café with warm lighting and vintage décor.",
    "A realistic portrait of a South Asian man with dark hair, a rugged beard, and piercing eyes. He wears a white shirt and a gray jacket, and the background is an industrial urban setting with concrete buildings and soft natural light.",
    "A hyper-realistic portrait of an East Asian woman with long, straight hair, soft brown eyes, and a peaceful expression. She wears a light blue dress, and the background is a serene lakeside with mist hovering over the water at dawn.",
    "A highly detailed portrait of a South Asian woman with dark brown eyes, long black hair, and a warm smile. She wears a traditional outfit with intricate patterns, and the background is a softly lit cultural market filled with bright colors.",
    "A realistic portrait of a young Chinese man with a calm demeanor, dark brown eyes, and short, spiky hair. His skin tone is medium, and he wears a black leather jacket. The background shows an urban street scene with soft evening light.",
    "A lifelike portrait of a woman from Southeast Asia with medium-length black hair, clear skin, and a serene expression. She wears a green blouse, and the background is a warm, sunny beach with waves gently rolling in.",
    "A hyper-realistic portrait of a Japanese man with short black hair, sharp features, and intense eyes. His expression is serious, and he wears a white dress shirt. The background features a sleek, modern office with soft ambient lighting.",
    "A realistic portrait of a young East Asian woman with medium-length wavy hair, delicate features, and dark brown eyes. She wears a casual denim jacket and a white top. The background is a vibrant city street with blurred traffic lights.",
    "A highly detailed portrait of a South Asian man with a clean-shaven face, dark brown eyes, and short hair. He wears a formal suit and tie, and the background is a luxurious office with glass windows and soft sunlight streaming through.",
    "A lifelike portrait of a Chinese woman with soft facial features, long black hair, and a gentle smile. She wears a white dress, and the background is a traditional temple with stone carvings and soft natural light.",
    "A realistic portrait of a Japanese man with light skin, black hair, and a subtle beard. His expression is calm and thoughtful, and he wears a black t-shirt. The background features a misty mountain scene with light filtering through the clouds.",
    "A hyper-realistic portrait of a South Asian woman with long black hair, deep brown eyes, and a serene smile. She wears a colorful sari, and the background is a lively marketplace with vibrant colors and soft light from hanging lanterns.",
    "A detailed portrait of an East Asian man with short, dark hair, a clean-shaven face, and a confident expression. He wears a dark suit with a tie, and the background is a minimalist office with bright natural light streaming through the windows.",
    "A lifelike portrait of a young South Asian woman with straight black hair, clear brown eyes, and a soft smile. She wears a casual red blouse, and the background is an outdoor café with lush greenery and soft sunlight.",
    "A realistic portrait of a Chinese man with short black hair, dark brown eyes, and a thoughtful expression. He wears a blue shirt, and the background is a peaceful lake surrounded by tall trees and morning mist.",
    "A hyper-realistic portrait of a Japanese woman with long, straight hair, soft skin, and a gentle expression. She wears a white kimono with floral patterns, and the background is a traditional Japanese temple with wooden pillars and lush greenery."
]

import os
save_dir = "flux-multimodal-asian"
os.makedirs(save_dir, exist_ok=True)
for i, prompt in enumerate(prompts):
    image = pipe(
        prompt = prompt,
        height=1024,
        width=1024,
        guidance_scale=3.5,
        num_inference_steps=50,
        max_sequence_length=512,
        generator=torch.Generator("cpu").manual_seed(0)
    ).images[0]
    image.save(f"{save_dir}/{i}.png")

# CUDA_VISIBLE_DEVICES=2 python flux_img.py